- hosts: all
  vars:
    root_dir: "{{playbook_dir}}/../public/ansible_developer_recipes"
    deploy_user: "{{ansible_user_id}}"
    mysql_root_user: root
    mysql_root_password: devroot
    apache_mode: prefork # use prefork or worker variables

    java_version: 8
    mailhog_version: 0.1.6
    mongo_version: 3
    nodejs_version: "6.x" # 0.10 0.12 4.x 5.x 6.x 7.x
    php_family: default # 5.4 | 5.5 | 5.6 | default
    php_xdebug_version: 2.3.3


    php_extensions:
      - { name: "php5-curl" }
      - { name: "php5-xsl" }
      - { name: "php5-memcache" }
      - { name: "php5-memcached" }


    vagrant_lvh_sites:
      - { type: "web",                                                                 # WSGI & LAMP sites supported
          name: "tools",                                                               # Name of the dev website
          path: "/vagrant/public/vagrant-tools",                                       # Path to site home folder
          # template: "{{playbook_dir}}/files/apache2/website.yml",                    # Provide custom template, uf builtin is not good
          aliases: [ "tools.vagrant.dev" ],                                            # These will be additional aliases to <<name>>.lvh.me
          vhost_overrides: ["SetEnv no-gzip 1", "RequestHeader unset Accept-Encoding"] # These lines will be added to website configuration file.
        }

  tasks:
     - include: "{{root_dir}}/tasks_mysql.yml"                                      # MySQL 5.5
     - include: "{{root_dir}}/tasks_apache.yml"                                     # apache prefork|worker
     - include: "{{root_dir}}/tasks_php_apt_switchversion.yml"                      # Selects preferred php family
     - include: "{{root_dir}}/tasks_php_apache.yml"                                 # php 5.5 for apache
     - include: "{{root_dir}}/tasks_nodejs.yml"                                     # node 6.x
     - include: "{{root_dir}}/tasks_memcached.yml"                                  # installs memcached service
     - include: "{{root_dir}}/tasks_sendmail.yml"                                   # Sendmail
     - include: "{{root_dir}}/tools/tasks_mailhog.yml"                              # Mailhog
     - include: "./tasks_phpextensions.yml"                                         # Installs custom php extensions
     - include: "{{root_dir}}/vagrant/tasks_vagrant_phpmyadmin.yml"                 # PhpMyAdmin
     - include: "{{root_dir}}/vagrant/tasks_vagrant_php_xdebug.yml"                 # XDebug extension
     - include: "{{root_dir}}/vagrant/tasks_vagrant_write_tools.yml"                # db import script, python venv init scripts
     - include: "{{root_dir}}/vagrant/tasks_vagrant_import_mysqldb_databag.yml"     # (re)imports databases from db folder
     - include: "{{root_dir}}/vagrant/tasks_vagrant_apache2_devsites.yml"           # register apache websites on vagrant


  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted
